language: dart
sudo: true

# Travis CI Issue: https://github.com/travis-ci/travis-ci/issues/8711
# Docker disables IPv6 in containers by default. Enable it for unit tests that need [::1].
before_script:
  # `daemon.json` is normally missing, but let's log it in case that changes.
  - sudo touch /etc/docker/daemon.json
  - sudo cat /etc/docker/daemon.json
  - sudo service docker stop
  # This needs YAML quoting because of the curly braces.
  - 'echo ''{"ipv6": true, "fixed-cidr-v6": "2001:db8:1::/64"}'' | sudo tee /etc/docker/daemon.json'
  - sudo service docker start
  # Fail early if docker failed on start -- add `- sudo dockerd` to debug.
  - sudo docker info
  # Paranoia log: what if our config got overwritten?
  - sudo cat /etc/docker/daemon.json

dart:
  - stable
  - dev

dart_task:
  - test: --platform vm
  - dartanalyzer
  - dartfmt

# 1.24 analyzer breaks on generic method syntax. Remove this exclusion when
# there is a new stable version.
matrix:
  exclude:
  - dart: stable
    dart_task: dartanalyzer

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
