language: dart
sudo: true

before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi

dart:
  - dev

dart_task:
  - test: --platform vm
  - dartanalyzer
  - dartfmt

# 1.24 analyzer breaks on generic method syntax. Remove this exclusion when
# there is a new stable version.
matrix:
  exclude:
  - dart: stable
    dart_task: dartanalyzer

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
